import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="h-screen w-full"
        style={{ background: `url(${"/layered-waves.svg"}) center/cover` }}
      >
        {/* main part of the page */}
        <div>
          <div className="flex items-center justify-center">
            <div className="absolute top-[40%] -mt-20 md:grid md:grid-cols-6 md:space-x-4">
              <div className="flex items-center justify-center md:col-span-3">
                <Image
                  src="/me.jpg"
                  className="h-32 w-32 overflow-hidden rounded-full md:col-span-3 md:h-72 md:w-72"
                  alt="Nice pic of me"
                  width={300}
                  height={390}
                />
              </div>
              <div className="col-span-3 flex items-center p-4 text-center">
                <div className="max-w-lg p-1 font-sans text-xl font-bold leading-8 text-white">
                  <p>Hi, Welcome to my blog!</p>
                  <p>
                    On this site, I'm posting the stories of a Full-Stack Web
                    developer
                  </p>
                  <p>
                    If you want to see my projects, or get to know me better,
                    visit:
                  </p>
                  <a href="https://theopoette.me">
                    <button className="m-4 rounded-lg border-4 border-indigo-900 bg-white py-2 px-4 font-sans font-bold text-indigo-900 transition-all duration-200 hover:bg-indigo-900 hover:text-white">
                      My website
                    </button>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
